import type { CommandCenterData } from "@/types/os";

const now = "2026-07-20T12:00:00.000Z";

export const mockCommandCenter: CommandCenterData = {
  northStar: {
    id: "ns-2026",
    year: 2026,
    statement:
      "Build tools and knowledge that help small teams do meaningful work — sustainably.",
    mission:
      "We serve agency founders, builders, and communities who need honest tech — not hype.",
    whyItMatters:
      "Every project we ship should leave someone better off: a client who runs smoother, a user who saves hours, a viewer who learns something real. Revenue follows work we're proud of — not the other way around.",
    updatedAt: now,
  },

  teamCapacity: {
    teamActiveLimit: 5,
  },

  members: [
    {
      id: "member-raj",
      email: "rajon@rajondey.com",
      name: "Rajon",
      role: "admin",
      kind: "core",
      activeLimit: 3,
    },
    {
      id: "member-gourob",
      email: "gourob@rdx.local",
      name: "Gourob",
      role: "member",
      kind: "core",
      activeLimit: 3,
    },
  ],

  pillars: [
    {
      id: "pillar-client",
      slug: "client-services",
      name: "Client Services",
      emoji: "💼",
      description: "Paid work for agencies & teams who need reliable delivery.",
      sortOrder: 1,
      activeSlotLimit: 2,
      leadId: "member-raj",
    },
    {
      id: "pillar-saas",
      slug: "saas",
      name: "SaaS",
      emoji: "🚀",
      description: "Products we own that solve problems at scale.",
      sortOrder: 2,
      activeSlotLimit: 2,
      leadId: "member-gourob",
    },
    {
      id: "pillar-content",
      slug: "content",
      name: "YouTube",
      emoji: "📺",
      description: "Free knowledge for builders — audience as a long-term asset.",
      sortOrder: 3,
      activeSlotLimit: 1,
      leadId: "member-raj",
    },
    {
      id: "pillar-research",
      slug: "research",
      name: "Research",
      emoji: "📄",
      description: "Papers & deep work that outlast any single client project.",
      sortOrder: 4,
      activeSlotLimit: 1,
      leadId: "member-gourob",
    },
  ],

  objectives: [
    {
      id: "obj-client-q3",
      pillarId: "pillar-client",
      year: 2026,
      quarter: 3,
      title: "Deliver excellent client work that teams rely on",
      outcome: "Clients run smoother — and we earn sustainably without chaos.",
      health: "yellow",
      sortOrder: 1,
    },
    {
      id: "obj-saas-q3",
      pillarId: "pillar-saas",
      year: 2026,
      quarter: 3,
      title: "Ship SaaS MVP and onboard first users",
      outcome: "Real people using something we built — proof the idea helps.",
      health: "yellow",
      sortOrder: 1,
    },
    {
      id: "obj-content-q3",
      pillarId: "pillar-content",
      year: 2026,
      quarter: 3,
      title: "Grow channel toward monetization threshold",
      outcome: "Thousands of builders learn from us for free.",
      health: "green",
      sortOrder: 1,
    },
    {
      id: "obj-research-q4",
      pillarId: "pillar-research",
      year: 2026,
      quarter: 4,
      title: "Submit two research papers",
      outcome: "Contribute knowledge the community can cite and build on.",
      health: "yellow",
      sortOrder: 1,
    },
    {
      id: "obj-client-q4",
      pillarId: "pillar-client",
      year: 2026,
      quarter: 4,
      title: "Stabilize retainer relationships",
      outcome: "Long-term partners, not one-off transactions.",
      health: "green",
      sortOrder: 2,
    },
  ],

  keyResults: [
    {
      id: "kr-client-revenue",
      objectiveId: "obj-client-q3",
      label: "Revenue closed",
      current: 12000,
      target: 40000,
      unit: "USD",
      updatedAt: now,
    },
    {
      id: "kr-client-projects",
      objectiveId: "obj-client-q3",
      label: "Projects delivered",
      current: 2,
      target: 6,
      unit: "projects",
      updatedAt: now,
    },
    {
      id: "kr-saas-users",
      objectiveId: "obj-saas-q3",
      label: "Paying users",
      current: 0,
      target: 10,
      unit: "users",
      updatedAt: now,
    },
    {
      id: "kr-saas-mvp",
      objectiveId: "obj-saas-q3",
      label: "MVP features shipped",
      current: 4,
      target: 8,
      unit: "features",
      updatedAt: now,
    },
    {
      id: "kr-content-subs",
      objectiveId: "obj-content-q3",
      label: "Subscribers",
      current: 820,
      target: 5000,
      unit: "subs",
      updatedAt: now,
    },
    {
      id: "kr-content-videos",
      objectiveId: "obj-content-q3",
      label: "Videos published",
      current: 6,
      target: 24,
      unit: "videos",
      updatedAt: now,
    },
    {
      id: "kr-research-papers",
      objectiveId: "obj-research-q4",
      label: "Papers submitted",
      current: 0,
      target: 2,
      unit: "papers",
      updatedAt: now,
    },
  ],

  projects: [
    {
      id: "proj-shuvvo",
      objectiveId: "obj-client-q3",
      title: "Shuvvo — billing & invoice flow",
      ownerId: "member-raj",
      collaboratorIds: ["member-gourob"],
      status: "active",
      priority: "p1",
      deadline: "2026-08-15",
      whoItHelps: "Shuvvo's team — less manual billing, fewer payment delays",
      fulfillmentNote:
        "When this ships, a real business stops chasing invoices and focuses on their work.",
      links: [
        { label: "Lead desk", url: "/dashboard" },
      ],
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-agency-site",
      objectiveId: "obj-client-q3",
      title: "Agency website rebuild",
      ownerId: "member-gourob",
      status: "active",
      priority: "p1",
      deadline: "2026-08-01",
      whoItHelps: "A 12-person marketing agency — clearer positioning online",
      fulfillmentNote:
        "Their team finally has a site that matches the quality they deliver to clients.",
      createdAt: "2026-06-15T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-crm-automation",
      objectiveId: "obj-client-q3",
      title: "Lead CRM automation",
      ownerId: "member-gourob",
      status: "backlog",
      priority: "p2",
      deadline: "2026-09-30",
      whoItHelps: "Prospect agency — tired of losing leads in spreadsheets",
      backlogReason: "Client slots full. Revisit when Shuvvo or agency site ships.",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-rdx-site",
      objectiveId: "obj-client-q3",
      title: "RDX marketing site v1",
      ownerId: "member-raj",
      status: "done",
      priority: "p1",
      deadline: "2026-06-02",
      whoItHelps: "Future agency clients — honest first impression of who we are",
      fulfillmentNote: "Warm outbound now has a credible home to point to.",
      completedAt: "2026-06-02T00:00:00.000Z",
      createdAt: "2026-04-01T00:00:00.000Z",
      updatedAt: "2026-06-02T00:00:00.000Z",
    },
    {
      id: "proj-saas-auth",
      objectiveId: "obj-saas-q3",
      title: "SaaS — auth & onboarding",
      ownerId: "member-gourob",
      collaboratorIds: ["member-raj"],
      status: "active",
      priority: "p1",
      deadline: "2026-07-25",
      whoItHelps: "First SaaS users — safe sign-up without friction",
      fulfillmentNote: "The front door to something we own and believe in.",
      links: [{ label: "GitHub", url: "https://github.com" }],
      createdAt: "2026-05-01T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-saas-billing",
      objectiveId: "obj-saas-q3",
      title: "SaaS — billing integration",
      ownerId: "member-gourob",
      status: "blocked",
      priority: "p1",
      deadline: "2026-08-10",
      whoItHelps: "Paying users — fair, simple pricing when they're ready",
      blockerNote: "Waiting on auth flow to merge before Stripe wiring.",
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-saas-dashboard",
      objectiveId: "obj-saas-q3",
      title: "SaaS — core dashboard",
      ownerId: "member-gourob",
      status: "active",
      priority: "p2",
      deadline: "2026-08-20",
      whoItHelps: "Daily users — the screen they'll open every morning",
      createdAt: "2026-06-10T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-yt-series",
      objectiveId: "obj-content-q3",
      title: "Agency ops tutorial series",
      ownerId: "member-raj",
      status: "active",
      priority: "p2",
      deadline: "2026-09-15",
      whoItHelps: "Solo founders & small agencies learning to systematize",
      fulfillmentNote: "Free education that compounds — helps people we'll never meet.",
      createdAt: "2026-05-15T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-yt-thumbnails",
      objectiveId: "obj-content-q3",
      title: "Thumbnail & title system",
      ownerId: "member-gourob",
      status: "done",
      priority: "p3",
      deadline: "2026-07-01",
      whoItHelps: "Viewers — clearer titles, less clickbait, more signal",
      completedAt: "2026-06-28T00:00:00.000Z",
      createdAt: "2026-05-01T00:00:00.000Z",
      updatedAt: "2026-06-28T00:00:00.000Z",
    },
    {
      id: "proj-paper-outline",
      objectiveId: "obj-research-q4",
      title: "Paper 1 — literature review",
      ownerId: "member-raj",
      status: "backlog",
      priority: "p2",
      deadline: "2026-10-31",
      whoItHelps: "Researchers & practitioners in our niche",
      backlogReason: "Q4 focus. Park until client + SaaS slots open up.",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-retainer-outreach",
      objectiveId: "obj-client-q4",
      title: "Retainer outreach — warm agencies",
      ownerId: "member-raj",
      status: "backlog",
      priority: "p2",
      deadline: "2026-11-30",
      whoItHelps: "Agencies who want a long-term dev partner",
      backlogReason: "Idea captured — review in Q4 planning, not now.",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "proj-invoice-tool-idea",
      objectiveId: "obj-saas-q3",
      title: "Invoice tool — internal idea",
      ownerId: "member-gourob",
      status: "backlog",
      priority: "p3",
      deadline: null,
      whoItHelps: "Freelancers drowning in manual invoicing",
      backlogReason: "Distraction logged. Good idea — wrong quarter. Revisit 2027.",
      createdAt: "2026-07-18T00:00:00.000Z",
      updatedAt: now,
    },
  ],

  wins: [
    {
      id: "win-1",
      projectId: "proj-rdx-site",
      title: "RDX site live — honest story for agencies",
      note: "Outbound finally has a home we're proud of",
      createdById: "member-raj",
      createdAt: "2026-06-02T00:00:00.000Z",
    },
    {
      id: "win-2",
      projectId: "proj-yt-thumbnails",
      title: "Thumbnail system shipped",
      createdById: "member-gourob",
      createdAt: "2026-06-28T00:00:00.000Z",
    },
    {
      id: "win-3",
      title: "Agency partner signed",
      note: "A team that trusts us with their public face",
      createdById: "member-raj",
      createdAt: "2026-06-20T00:00:00.000Z",
    },
    {
      id: "win-4",
      title: "820 subscribers learning for free",
      note: "Real people watching real tutorials",
      createdById: "member-raj",
      createdAt: "2026-07-15T00:00:00.000Z",
    },
  ],

  focusProjectIds: ["proj-shuvvo", "proj-saas-auth", "proj-agency-site"],

  checkIns: [
    {
      id: "checkin-1",
      memberId: "member-raj",
      weekStart: "2026-07-14",
      moved: "Shuvvo billing flow 80%, recorded 2 YouTube scripts",
      next: "Finish Shuvvo invoices, review agency site copy",
      confidence: 4,
      energy: 3,
      createdAt: "2026-07-14T09:00:00.000Z",
    },
    {
      id: "checkin-2",
      memberId: "member-gourob",
      weekStart: "2026-07-14",
      moved: "SaaS auth PR merged, agency site homepage done",
      next: "Auth edge cases, dashboard shell",
      blockers: "Waiting on design tokens for dashboard",
      confidence: 4,
      energy: 4,
      createdAt: "2026-07-14T10:30:00.000Z",
    },
  ],

  capacityOverrides: [],

  quarterlyReview: {
    year: 2026,
    quarter: 3,
    learnings: "",
    completedSteps: [],
    updatedAt: now,
  },
};
